// Opções na landing page
export const USER_CREATE_ACCOUNT = "USER_CREATE_ACCOUNT";
export const USER_CREATE_ACCOUNT_SUCCESS = "USER_CREATE_ACCOUNT_SUCCESS";
export const USER_CREATE_ACCOUNT_FAILED = "USER_CREATE_ACCOUNT_FAILED";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";

export const USER_UPDATE_DATA = "USER_UPDATE_DATA";

//My account page
export const USER_CHANGE_PROFILE_PICTURE = "USER_CHANGE_PROFILE_PICTURE";
export const USER_CHANGE_PROFILE_DATA = "USER_CHANGE_PROFILE_DATA";
