// Opções na landing page
export const USER_CREATE_ACCOUNT = "USER_CREATE_ACCOUNT";
export const USER_LOGIN = "USER_LOGIN";
export const USER_FORGOT_PASSWORD = "USER_FORGOTPASSWORD";

//My account page
export const USER_CHANGE_PROFILE_PICTURE = "USER_CHANGE_PROFILE_PICTURE";
export const USER_CHANGE_PROFILE_DATA = "USER_CHANGE_PROFILE_DATA";
