export const LOADING = "LOADING";

// Opções na landing page
export const USER_CREATE_ACCOUNT_SUCCESS = "USER_CREATE_ACCOUNT_SUCCESS";
export const USER_CREATE_ACCOUNT_FAILED = "USER_CREATE_ACCOUNT_FAILED";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";

export const USER_GET_DATA_SUCCESS = "USER_GET_DATA_SUCCESS";
export const USER_GET_DATA_FAILED = "USER_GET_DATA_FAILED";

export const USER_UPDATE_DATA_SUCCESS = "USER_UPDATE_DATA_SUCCESS";
export const USER_UPDATE_DATA_FAILED = "USER_UPDATE_DATA_FAILED";


//My account page
export const USER_GET_PROFILE_PICTURE_SUCCESS = "USER_GET_PROFILE_PICTURE_SUCCESS";
export const USER_GET_PROFILE_PICTURE_FAILED = "USER_GET_PROFILE_PICTURE_FAILED";

export const USER_UPLOAD_PROFILE_PICTURE_SUCCESS = "USER_UPLOAD_PROFILE_PICTURE_SUCCESS";
export const USER_UPLOAD_PROFILE_PICTURE_FAILED = "USER_UPLOAD_PROFILE_PICTURE_FAILED";

export const USER_CHANGE_PROFILE_PICTURE = "USER_CHANGE_PROFILE_PICTURE";

